import type { SessionResult } from "@ainterview/shared";
import type {
  AiInterviewProvider,
  ContinueInterviewInput,
  ContinueInterviewResult,
  FinalizeInterviewInput,
  GenerateTemplateResult,
  StartInterviewInput,
  StartInterviewResult,
} from "./types.js";

const clamp = (value: number, min: number, max: number) => Math.min(max, Math.max(min, value));

export class MockAiProvider implements AiInterviewProvider {
  async startInterview(input: StartInterviewInput): Promise<StartInterviewResult> {
    const target = clamp(6, input.minQuestionCount, input.maxQuestionCount);
    return {
      rubric: {
        communication: 25,
        technical_depth: 40,
        problem_solving: 35,
      },
      plannedCoverage: [
        `${input.templateCategory} fundamentals`,
        "real-world tradeoffs",
        "debugging and communication",
      ],
      plannedQuestionCount: target,
      firstQuestion: `Let's start: briefly introduce your approach to ${input.templateTitle}.`,
    };
  }

  async continueInterview(input: ContinueInterviewInput): Promise<ContinueInterviewResult> {
    const answered = input.turns.length;
    const shouldFinish =
      answered >= input.maxQuestionCount || answered >= input.plannedQuestionCount;

    if (shouldFinish) {
      return {
        decision: "finish",
        reasoning: "Target coverage reached.",
      };
    }

    return {
      decision: "continue",
      reasoning: "Need one more signal for confidence.",
      nextQuestion: `Question ${answered + 1}: explain a tradeoff you made recently and why.`,
    };
  }

  async generateTemplate(prompt: string): Promise<GenerateTemplateResult> {
    return {
      title: `AI Generated: ${prompt.slice(0, 30)}...`,
      category: "Engineering",
      description:
        "This template was generated by AI based on your description. It covers the key areas you requested and provides a structured interview experience.",
      systemInstruction:
        "You are an experienced technical interviewer. Ask clear, relevant questions based on the candidate's background. Evaluate answers fairly and provide constructive feedback.",
    };
  }

  async finalizeInterview(input: FinalizeInterviewInput): Promise<SessionResult> {
    const base = 60;
    const bonus = Math.min(35, input.turns.length * 4);
    const score = Math.min(100, base + bonus);

    return {
      score,
      feedback: {
        strengths: ["Structured explanations", "Clear communication"],
        weakAreas: ["More concrete metrics in examples"],
        suggestions: ["Answer with STAR format.", "Add impact numbers when describing outcomes."],
        summary:
          input.completionReason === "user_stopped"
            ? "Session ended by user. Partial evaluation generated."
            : "Adaptive interview completed with sufficient signal.",
      },
    };
  }
}
